import { Breadcrumb } from '@/components/primitives/Breadcrumb';
import { Button } from '@/components/primitives/Button';
import { Container } from '@/components/primitives/Container';
import { Eyebrow } from '@/components/primitives/Eyebrow';
import { Heading } from '@/components/primitives/Heading';
import { Link } from '@/components/primitives/Link';
import { Prose } from '@/components/primitives/Prose';
import { Section } from '@/components/primitives/Section';
import { Blocks } from '@/components/content/Blocks';
import { DataRows } from '@/components/content/DataRows';
import {
  CAPABILITY_GROUPS,
  CONTACT_CTA,
  ENQUIRY_CTA,
  enquiryHref,
} from '@/lib/services/architecture';
import type { Division, ServiceDetail as ServiceRecord } from '@/lib/sanity/queries';
import styles from './content.module.css';

/**
 * The service page body, shared by `/design/services/[slug]`, `/digital/services/[slug]` and
 * `/press/services/[slug]` — `GS-P04`.
 *
 * ## One template, three divisions
 *
 * `GS-P03` left Digital as the only division with per-service routes, which made service
 * discovery inconsistent: a Design visitor got a card with no page behind it. The choice at
 * `GS-P04` was one data-driven template or three bespoke ones, and the brief asked for the
 * leanest coherent answer.
 *
 * It is one template because the *questions* a service page answers do not vary by division —
 * what the service is, what Gridsmith can do within it, how the engagement runs, what it
 * connects to, and how to start a conversation about it. What varies is the voice, and the
 * voice is already carried entirely by the theme the route group's root layout set on
 * `<html data-division>`. Nothing in this file names a colour, a typeface or a division-specific
 * rule; the same markup reads as a drawing sheet on Design, a spec sheet on Digital and a
 * printed page on Press. That is `CLAUDE.md`'s "shared structure, not shared colour", and
 * writing it three times would have produced three drifting copies of one page.
 *
 * ## What the page does not need
 *
 * **No price** (`GS-D002`), **no portfolio, case study or client evidence** (`GS-D001`). A
 * record with only a title and a group renders a complete, honest page: every block below is
 * conditional, and the CTA is always present. The page argues from what the service is and how
 * the work runs, which is the credibility model `SERVICE-ARCHITECTURE.md` §7 sets out.
 *
 * ## Exclusions render, they do not disappear
 *
 * `deliverable.included` is a boolean, and a `false` is content rather than an absence. A
 * filtered-out exclusion is indistinguishable from one nobody thought of — and on these pages
 * the exclusions are load-bearing: they are where Technical says it does not certify drawings
 * and Press says it cannot promise a retailer listing.
 *
 * ## The CTA carries context and its destination is not editable
 *
 * The label is the division default unless the record overrides it; the href is always the
 * enquiry form with `division` and `service` set (`lib/services/architecture.ts`), and the form
 * records both on the lead through the unchanged GS-P01 server-only writer. The universal
 * secondary route is plain contact.
 *
 * Server Component, zero client JS, statically generated by its routes.
 */
const DIVISION_NAMES: Record<Division, string> = {
  design: 'Gridsmith Design',
  digital: 'Gridsmith Digital',
  press: 'Gridsmith Press',
};

/** Where a division's per-service pages live. All three exist since `GS-P04`. */
export const SERVICE_BASE_PATH: Record<Division, string> = {
  design: '/design/services',
  digital: '/digital/services',
  press: '/press/services',
};

export function ServiceDetail({ service }: { service: ServiceRecord }) {
  const division = service.division;
  const group = CAPABILITY_GROUPS.find((g) => g.key === service.capabilityGroup);
  const capabilities = service.capabilities ?? [];
  const included = service.deliverables?.filter((d) => d.included) ?? [];
  const excluded = service.deliverables?.filter((d) => !d.included) ?? [];
  const stages = service.process ?? [];
  const collaborators = (service.collaborators ?? []).filter((d) => d !== division);
  const related = service.relatedServices ?? [];

  return (
    <main id="main" tabIndex={-1}>
      <Section rhythm="loose">
        <Container>
          <Breadcrumb
            items={[
              { href: '/', label: 'Home' },
              { href: `/${division}`, label: DIVISION_NAMES[division].replace('Gridsmith ', '') },
              { href: `${SERVICE_BASE_PATH[division]}/${service.slug}`, label: service.title },
            ]}
          />
          {group ? <Eyebrow>{group.label}</Eyebrow> : null}
          <Heading level={1}>{service.title}</Heading>
          {service.problem || service.description ? (
            <Prose>
              {service.problem ? <p>{service.problem}</p> : null}
              <Blocks value={service.description} />
            </Prose>
          ) : null}
        </Container>
      </Section>

      {capabilities.length > 0 ? (
        <Section surface="sunken" labelledBy="capabilities">
          <Container>
            <Heading level={2} id="capabilities">
              What this covers
            </Heading>
            {/* Names, not claims. Each is an approved capability from lib/services/catalogue.ts,
                carried on the record so the list is CMS content rather than compiled in. */}
            <ul className={styles.capabilityList}>
              {capabilities.map((capability) => (
                <li key={capability} className={styles.capability}>
                  {capability}
                </li>
              ))}
            </ul>
          </Container>
        </Section>
      ) : null}

      {included.length > 0 ? (
        <Section>
          <Container>
            <Heading level={2} id="included">
              What you get
            </Heading>
            <DataRows
              label="What you get"
              items={included.map((d) => ({
                label: d.label,
                value: 'Included',
                rationale: d.detail ?? undefined,
              }))}
            />
          </Container>
        </Section>
      ) : null}

      {excluded.length > 0 ? (
        <Section>
          <Container>
            <Heading level={2} id="not-included">
              What you do not get
            </Heading>
            <DataRows
              label="What you do not get"
              items={excluded.map((d) => ({
                label: d.label,
                value: 'Not included',
                rationale: d.detail ?? undefined,
              }))}
            />
          </Container>
        </Section>
      ) : null}

      {stages.length > 0 ? (
        <Section>
          <Container>
            <Heading level={2} id="process">
              How it runs, and what it asks of you
            </Heading>
            <Prose>
              <p>
                The six stages are the same on every Gridsmith engagement. Where your own time is
                listed, it is the part of a project that is worth knowing before it starts.
              </p>
            </Prose>
            <DataRows
              label="Process stages and your time"
              items={stages.map((s) => ({
                label: `${s.number}. ${s.title}`,
                value: [s.duration, s.clientTime ? `you: ${s.clientTime}` : null]
                  .filter(Boolean)
                  .join('  ·  '),
                rationale: s.divisionDetail ?? s.description ?? undefined,
              }))}
            />
          </Container>
        </Section>
      ) : null}

      {collaborators.length > 0 || related.length > 0 ? (
        <Section labelledBy="related">
          <Container>
            <Heading level={2} id="related">
              Across Gridsmith
            </Heading>
            {collaborators.length > 0 ? (
              <Prose>
                <p>
                  This service draws on{' '}
                  {collaborators.map((d, i) => (
                    <span key={d}>
                      {i > 0 ? ' and ' : ''}
                      <Link href={`/${d}`}>{DIVISION_NAMES[d]}</Link>
                    </span>
                  ))}
                  . Your engagement stays with {DIVISION_NAMES[division]}.
                </p>
              </Prose>
            ) : null}
            {related.length > 0 ? (
              <ul className={styles.relatedList}>
                {related.map((r) => (
                  <li key={`${r.division}-${r.slug}`}>
                    <Link href={`${SERVICE_BASE_PATH[r.division]}/${r.slug}`}>{r.title}</Link>
                  </li>
                ))}
              </ul>
            ) : null}
          </Container>
        </Section>
      ) : null}

      <Section rhythm="loose">
        <Container>
          <div className={styles.serviceCtas}>
            <Button href={enquiryHref(division, service.slug)}>
              {service.ctaLabel ?? ENQUIRY_CTA[division]}
            </Button>
            <Button href={CONTACT_CTA.href} variant="secondary">
              {CONTACT_CTA.label}
            </Button>
          </div>
        </Container>
      </Section>
    </main>
  );
}
